### PR TITLE
add drone & kubectl-warp

### PR DESCRIPTION
**Pull request by izzatzr**
## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/tomhuang12/awesome-k8s-resources/blob/master/contributing.md).

## Describe Why This Is Awesome

Why is this awesome?

--

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Comment by tomhuang12** [comment]
Thank you for the PR! I haven't heard of drone before. How does it integrate with k8s?

**Comment by izzatzr** [comment]
> Thank you for the PR! I haven't heard of drone before. How does it integrate with k8s?

the easier way to integrate drone is by installing this helm chart
https://github.com/drone/charts

**Comment by tomhuang12** [comment]
Thanks for the link! From what I understood, drone is a CI tool for docker containers, not necessarily specific for k8s. Even though it can work with k8s by integrating with a CD tool, I wouldn’t consider this a k8s tool. For example, Jenkins can also build containers, but it’s not specifically built to work with k8s (not considering Jenkins k8s plug-in). Correct me if I’m wrong.

**Comment by tomhuang12** [comment]
Kubectl warp is no doubt a good k8s tool!

**Comment by izzatzr** [comment]
> Thanks for the link! From what I understood, drone is a CI tool for docker containers, not necessarily specific for k8s. Even though it can work with k8s by integrating with a CD tool, I wouldn’t consider this a k8s tool. For example, Jenkins can also build containers, but it’s not specifically built to work with k8s (not considering Jenkins k8s plug-in). Correct me if I’m wrong.

i've removed drone from the list . Ok i agree what you said here based on my previous experience , i need to use some specific plugin in order to integrate with my k8s .

**Comment by tomhuang12** [comment]
I appreciate the PR!

**Pull request merged**
