### PR TITLE
feat: add kubernetes in a visual way and how to pass CKAD exam

### PR DESCRIPTION
**Pull request by scraly**
## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/tomhuang12/awesome-k8s-resources/blob/master/contributing.md).

## Describe Why This Is Awesome

Why is this awesome?

--

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Review by tomhuang12 — CHANGES_REQUESTED** [review]
Thanks for the PR! Please only add the same resource once in the list :). Kubernetes in a visual way, with sketchnotes falls under Learnings and Documentations.

**Comment by scraly** [comment]
Hi,
I removed the link from guide section

**Review by tomhuang12 — CHANGES_REQUESTED** [review]
Could you remove your changes on table of contents?

**Comment by tomhuang12** [comment]
Closing due to no response

**Pull request closed without merging**
