### PR TITLE
add cka, cks resource repos

### PR DESCRIPTION
**Pull request by walidshaari**
- add cka repo with 2.4k stars
- add cks repo updated as exam approaches with authentic verified sources.

## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/tomhuang12/awesome-k8s-resources/blob/master/contributing.md).

## Describe Why This Is Awesome

Why is this awesome?
-----

the CKA/CKS repos both were created at the beta time of the initial exam release, CKA in 2017 now with 2.4K stars and almost 1000 forks, CKS is still beta, however, feedback from beta testers and well-known community contributors are adding to it periodically. by the time the exam will be released on mid-Nov 2020. it will prove to be one of the authentic free community resources to follow to take the exam and continue the journey beyond the exam

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Review by tomhuang12 — CHANGES_REQUESTED** [review]
This is awesome! Could you take out the :fire: to keep format consistent in that section?

**Comment by walidshaari** [comment]
from both enteries? the CKS and CKA?

**Review by walidshaari — COMMENTED** [review]
remove  the fire icons from both items, the CKA and CKS

**Review by tomhuang12 — APPROVED** [review]
Thank you for the PR!

**Comment by walidshaari** [comment]
thank you @tomhuang12 for being awesome ;-)

**Pull request merged**
