### PR TITLE
Add Kube Karp to the Networking section

### PR DESCRIPTION
**Pull request by immanuelfodor**
## Why This Is Awesome? 

[Kube Karp](https://github.com/immanuelfodor/kube-karp)'s unique feature is that it can load balance the Kube API Server without external tools which other LB solutions can not do at the time of writing (e.g., Porter, MetalLB). It does not provide `LoadBalancer` resources for exposed services, it only manages a floating virtual IP accross nodes in the same subnet, so you can always reference the cluster with the same IP address.

--

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Comment by tomhuang12** [comment]
Hello @immanuelfodor, thanks for your contribution! Looks like it is a new project. I am going to leave this open for community feedback :)! The tool definitely looks cool. I will personally try it out sometimes!

**Comment by immanuelfodor** [comment]
Yes, it's fairly new. I solved a problem with it that we faced in production last month as [Nagios k8s checks](https://github.com/agapoff/check_kubernetes) would use just one node IP otherwise. If that node would go down, all the checks would fail. Using the tool I could provide the virtual IP of the k8s API server to Nagios without any external load balancing, and it's working fine since then. Our developers have also switched to the virtual IP in their kubeconfig files since then in all environments, so they similarly don't depend on any node's IP when running `kubectl` commands.

**Comment by immanuelfodor** [comment]
Update: Kube Karp is gaining attention day by day (no marketing or whatsoever, only organic), 3 contributors and 35 stars as of now. Go, little project, go! :)

**Comment by immanuelfodor** [comment]
52 stars! Added a :fire:

**Comment by tomhuang12** [comment]
Awesome!! Thanks!

**Pull request merged**
