### PR TITLE
Add KubeHelper to Miscellaneous List.

### PR DESCRIPTION
**Pull request by JWebDev**
KubeHelper - simplifies many daily Kubernetes cluster tasks through a web interface. Search, analysis, run commands, cron jobs, reports, filters, git synchronization and many more.

### CODE REVIEW

**Comment by tomhuang12** [comment]
Thank you for the contribution! I am going to leave this open for community feedback as it doesn't have 50 stars yet :).

**Comment by JWebDev** [comment]
> Thank you for the contribution! I am going to leave this open for community feedback as it doesn't have 50 stars yet :).

)))) Almost. I just made the project public yesterday.

**Comment by tomhuang12** [comment]
Awesome! Could you put it in the right alphabetical order please? Thanks!

**Comment by tomhuang12** [comment]
Thank you!

**Pull request merged**
