### PR TITLE
Add habitus, copper, starter, trackman and konfig to awesome-k8s-resources

### PR DESCRIPTION
**Pull request by Kasia66**
## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/tomhuang12/awesome-k8s-resources/blob/master/contributing.md).

## Describe Why This Is Awesome

Why is this awesome?

- Habitus (https://github.com/cloud66-oss/habitus) - A build flow tool for Docker.
- Cooper (https://github.com/cloud66-oss/copper) - A configuration file validator for Kubernetes.
- Starter (https://github.com/cloud66-oss/starter) - Generates a Dockerfile & a docker-compose.yml file from arbitrary source code.
- Trackman (https://github.com/cloud66-oss/trackman) - Execute commands as a workflow.
- Konfig (https://github.com/cloud66-oss/konfig) - A Kubernetes friendly Rails configuration gem.

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Review by tomhuang12 — CHANGES_REQUESTED** [review]
Thanks for the PR! 

Cooper and Konfig are good additions to the list! The others I think are not really Kubernetes specific and can work with any other platform. Could you create a PR with just Cooper and Konfig please?

Also, the additions you made are in the wrong file. Can you make them in README.md in the corresponding sections?

**Comment by Kasia66** [comment]
Thank you, Tom. 
Can you also let me know if this project can be added? 
- Alterant (https://github.com/cloud66-oss/alterant)- A simple Kubernetes configuration modifier.

**Comment by tomhuang12** [comment]
Since it is less than 50 stars, I would leave that out and create another PR for it. The others are good to add.

**Review by tomhuang12 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
